name: ai-job-trends
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - requests
  - beautifulsoup4
  - lxml
  - sqlalchemy
  - pandas
  - pyyaml
  - tqdm
  - pip
  - pip:
      - playwright
      - spacy
      - nltk
      - plotly
      - streamlit
